---
Name: elemental_site_search
After: 'elemental'
---
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - jbennecker\ElementalSiteSearch\ContentControllerSearchExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - jbennecker\ElementalSiteSearch\SiteTreeSearchExtension
